googleapis/google-api-python-client

googleapiclient/http.py
If the file you're downloading via `MediaIoBaseDownload` from Google Cloud Storage is smaller than the `DEFAULT_CHUNK_SIZE` then `self._total_size` was never getting set thus `self._done` was never getting set to `True`.
This would cause code like this to hang forever (even though the file was actually fully downloaded)
request = farms.animals().get_media(id='super_small_file') # File smaller than DEFAULT_CHUNK_SIZE
fh = io.FileIO('cow.png', mode='wb')
downloader = MediaIoBaseDownload(fh, request)
done = False
while done is False:
status, done = downloader.next_chunk() # this done will never be True
if status:
print "Download %d%%." % int(status.progress() * 100)
print "Download Complete!"
I was able to fix this locally with the change in this pull request. That is, if content-range is …
=> MediaIoBaseDownload hangs forever when object to download is smaller than DEFAULT_CHUNK_SIZE

.travis.yml, googleapiclient/http.py
It turns out that the same code in `http.py` is used for processing both (1)
the initial response and redirect and (2) the replies containing actual bytes
for download. This means that the new exception we added for (2) leads to
problems in (1).
=> Remove a newly-added exception.

googleapiclient/discovery.py, tests/test_discovery.py
Currently, if we have a top-level methodPath of the form `path:methodName`,
we'll pass this to `urlparse.urljoin`, where this is interpreted as
`scheme:netloc`. In cases other than media upload, this is **not** what we
want.
This fixes the issue by adding our own custom `urljoin`, which detects and
handles this case. We also add a test.
PTAL @nathanielmanistaatgoogle
=> Support methodPath entries containing colon.

apiclient/__init__.py, googleapiclient/discovery.py, googleapiclient/http.py, googleapiclient/model.py, googleapiclient/sample_tools.py, tests/test_discovery.py, tests/test_http.py, tests/test_json_model.py, tests/test_protobuf_model.py, tests/test_schema.py
Got the code to pass all of the tests in python 2.6, 2.7, 3.3, and 3.4.
Removed 1 questionable test and having another test bypassed if in python 3. (see 2 of the later commits for more info)
=> Python3 module updates

.travis.yml, tox.ini
Setting up test environment for 3.3 and 3.4.  Expect lots of red for now.
=> Python3 configuration

setup.py
Updating setup.py file to include Python3.
1. I used the latest version (1.4.6) of oauth2client, although 1.4 was the version the introduced Py3 support.
2. I changed the Operating System to OS Independent since it is.  I'm not sure if I should put this in a separate PR or commit since it's not needed for Py3, but it's only one line.
3. I'll leave updating the version number and documentation up to you Googlers since you will be the ones pushing this out.
=> Including changes for Python3 in setup.py

googleapiclient/errors.py, googleapiclient/http.py, tests/test_discovery.py, tests/test_errors.py, tests/test_http.py, tests/test_json_model.py, tests/test_mocks.py
1) HttpError parses http response by json.loads. It accepts only
unicode on PY3 while response is bytes. So decode response first.
2) BatchHttpRequest uses email.parser.FeedParser. It accepts only
unicode on PY3, too. So encode parsed response to emulate normal
http response.
=> Fix unicode issues in HttpError and BatchHttpRequest

samples/audit/audit.py
The call to build(api, version, http) to setup the service stub is unneeded since the call to sample_tools.init above does that for the sample.  Plus the build function was not imported from apiclient.discovery which causes this sample to not work at all.
=> Removed unneeded/unused line of code

.coveragerc, .gitignore, .travis.yml, tox.ini
Run coverage with all tests and send results to coveralls.io.
This was added to oauth2client and I figured we should add it here as well.
=> Adding coveralls integration

googleapiclient/http.py, tests/test_http.py
As per the [docs](https://developers.google.com/api-client-library/python/guide/mocks), the `MockHttp` object can be created as follows:
`http = HttpMock('books-discovery.json', {'status': '200'})`
The default headers for `HttpMock` currently returns a string, which causes `httplib2` to throw an exception:
`ValueError: invalid literal for int() with base 10: '200 OK'`
The relevant line from `httplib2` can be found here: https://github.com/jcgregorio/httplib2/blob/master/python2/httplib2/__init__.py#L1687
=> Don't include reason in default HttpMock headers

samples/adexchangebuyer/README.md, samples/dfareporting/README.md
Proposal
===
Update the copyright years on some files to 2015. Update some .md files to use better header formatting.
Reasoning
===
The nature of this PR should be self-explanatory but, just incase, we are currently in the year 2015 and the copyright years should reflect such as this is still an active project. The header style change in the .md files preserves the intended visual but uses a more easily editable method (no one wants to keep typing === under every letter of the header).
=> Minor Markdown Fix

googleapiclient/http.py, tests/test_http.py
When forming a multipart/mixed HTTP request like the ones created using
the BatchHttpRequest object, the request is supposed to include two
trailing newlines to signify:
1. The termination of the HTTP headers for each wrapped request.
2. The empty body of the wrapped request.
Without this change some implementations of API servers were rejecting
requests generated by this client.  Specifically requests which had an
empty wrapped request body.
=> Stop stripping newlines from batch requests

googleapiclient/discovery.py, tests/data/zoo.json, tests/test_discovery.py
This method can be used to get a BatchHttpRequest object with the
batch_uri calculated from the rootUrl and batchPath fields from the
discovery doc.
Without this change, users have to know what the batch url for newer api
endpoints is.  For example:
batch = BatchHttpRequest(batch_uri=http://zoo.googleapis.com/batch)
With this change, the syntax is easier:
zoo = build('zoo', 'v1', http=http)
batch = zoo.new_batch_http_request()
=> Add a new_batch_http_request() method to services

googleapiclient/discovery.py
This comment doesn't actually show up in the generated epydoc, but it
does allow the "make docs" command to complete, and it is nice to have
the explanation of how to use the method in the source repository.
=> Adds a doc comment for new_batch_http_request

googleapiclient/discovery.py, tests/test_discovery.py
discovery.build()'s http parameter is optional, but if you call build_from_document directly it doesn't handle the case where http is None. Fixed that so now you can call ``discovery.build_from_document(doc, credentials=credentials)``.
=> Making http parameter in discovery.build_from_document optional.

googleapiclient/discovery.py, tests/test_discovery.py
Sending nextPageToken out with an empty string to Google's DFA API will
raise a 500 error. This commit treats an empty nextPageToken field the
same as it not existing at all so that method.list_next() will not
attempt to retrieve a non-existent page of results.
=> Discovery: Treat empty nextPageToken field the same as it not existing

googleapiclient/http.py, tests/test_http.py
The batch execute when not given an http object will look into the given requests. If no request was given, it will raise a `ValueError("Missing a valid http object.")`.
=> return if the batch is empty

samples/django_sample/plus/views.py
Use render method to render the view as it is a replacement for 
render_to_response.
Exclude backward compatibility for render_to_response method as 
developers using it are likely to be on one of the latest versions of 
Django that has support for render method. Therefore, render_to_response
support may be excluded altogether from this sample project.
=> Upgrade django sample project to use render method

googleapiclient/http.py, tests/data/bad_request.json, tests/test_http.py
Fixes #124.
I decided to write the test for the functionality I was actually trying to use, and which was previously not covered by tests: using ``HttpMock`` specifically to mock error responses. The side effect is that it exposes how ``HttpMock`` was not not reading content as bytes on Python 3 and causing a confusing exception to be thrown.
I think the fix speaks for itself...
=> Force HttpMock to read content from file as bytes

googleapiclient/discovery.py, googleapiclient/discovery_cache/__init__.py, googleapiclient/discovery_cache/appengine_memcache.py, googleapiclient/discovery_cache/base.py, googleapiclient/discovery_cache/file_cache.py, tests/test_discovery.py, tests/test_discovery_cache.py, tox.ini
Added 2 keyword arguments; cache_discovery and cache. You can suppress caching by setting cache_discovery=False. You can inject your own caching module via the cache kwarg.
It automatically uses app engine memcache if it's detected. It's not a hard dependency. Then fall back to file based caching.
fixes #110
=> Implemented automatic caching for the discovery documents.

googleapiclient/discovery.py, tests/test_discovery.py
1. `Generator` and `StringIO` are replaced by `BytesGenerator` and `BytesIO`.  If `BytesGenerator` doesn't exist (as is the case in Python 2), fall back to Generator.
2. `BytesGenerator` is buggy (see [#18886](https://bugs.python.org/issue18886) and [#19003](https://bugs.python.org/issue19003)) and corrupts `\r` into `\n`.  To work around this, we implement a patched version of `BytesGenerator` that replaces `._write_lines` with just `.write`.
Note: `BytesGenerator` was introduced in Python 3.2.  This is OK since the library already demands 3.3+.
The `test_multipart_media_good_upload` has been updated to reflect the change.  It is also stricter now, as it matches the entire request body against the expected form.
Fixes #145.
---
This ensures that `body` is of type `bytes` rather than …
=> Fix non-resumable binary uploads on Python 3

googleapiclient/http.py, tests/test_http.py
The function mimetypes.guess_type returns (None, None) if it fails to
find a matching extension. In that case, we should just treat the media
as application/octet-stream.
=> Default to octet-stream if mimetype detection fails.

googleapiclient/http.py, tests/test_http.py
This is a re-created pull request #159 to make sure that commit author and pull requests are the same accounts so that CLA bot is not confused. This is going to address issues #71, #97, #158.
=> Handle SSL errors with retries

samples/calendar_api/calendar_sample.py
The original:
* Violated pep8
* Used `print()` both as a statement and as a function, guaranteeing that the code won't work in either Python 2.5 or 3.x
* Didn't explain anything about what was happening.
This change fixes two of those problems.
=> pep8 + print statement alignment

samples/django_sample/plus/views.py
The v2.0.0 release moved a xsrfutil module to a subpackage of oauth2client
called contrib
=> Make compatible with oauth2client v2.0.0 (xsrfutil)

googleapiclient/discovery.py, tests/test_discovery.py
Fallback to use new discovery uri pattern when the old one fails.
=> Fallback to use new discovery uri pattern when the old one fails.

googleapiclient/__init__.py, googleapiclient/discovery_cache/__init__.py, googleapiclient/discovery_cache/appengine_memcache.py, googleapiclient/discovery_cache/file_cache.py, googleapiclient/http.py, googleapiclient/model.py, tests/test_json_model.py
This pull request is a fixed version of #174
=> move logging into __name__-specific loggers from the root logger

googleapiclient/discovery_cache/file_cache.py, setup.py, tox.ini
Be compatible with older oauth2client versions. This simplifies
the installation (also for downstream) when software needs an older
oauth2client version but also wants to use googleapiclient.
=> Allow using oauth2client versions < 2

googleapiclient/http.py
Fix #191 by adding a guard when importing `ssl`, and replace all direct
references to `SSLError` (the sole member of `ssl` being used) with a
shim, `_ssl_SSLError`. It is prefixed with a '_' to caution users
against relying on the name when importing `googleclient.http`.
`httplib2` also takes the same approach (see `ssl_SSLError` in
`httplib2/__init__.py`), but instead of using `None` when faking
`SSLError`, we provide a 'real' class, so that code can continue to
trigger the exception handler for `SSLError` in `googleclient.http` (eg.
in tests, `SSLError`'s are raised). If the shim `_ssl_SSLError` were
`None`, an exception handler for it would not catch anything, as `None`
is not a class and we could never throw anything that could be
"compatible" with `None` [1]
[1] …
=> googleapiclient.http: guard when importing ssl

googleapiclient/http.py, tests/test_http.py
=> Obtain initial access_token if necessary in BatchHttpRequest.execute()

googleapiclient/channel.py, googleapiclient/discovery.py, googleapiclient/errors.py, googleapiclient/http.py, googleapiclient/schema.py, setup.py, tox.ini
=> Add support for oauth2client >= 3.0.0, < 4.0.0.

googleapiclient/discovery.py
See https://github.com/google/google-api-python-client/issues/208 .
If HttpMock or HttpMockSequence is used in a test without the cache
being filled first, a strange KeyError will be thrown. This happens
on e.g. Travis CI. Unfortunately this behavior is used in the tests;
this patch adds a warning for those unfortunate enough to encounter
it.
=> Add a warning when using mocking without cache.

README.md, setup.py
As of uritemplate 3.0.0 and uritemplate.py 3.0.2, the two packages are equivalent.
There were no changes to functionality; see
https://github.com/sigmavirus24/uritemplate/blob/master/HISTORY.rst.
This resolves the conflict described in https://github.com/google/google-api-python-client/issues/57.
=> upgrade to unified uritemplate 3.0.0 [closes #57]

README.md
Change the wording to explicitly mention that Python 3.3 and 3.4 are supported (instead of saying "3.3+"), as these are the versions that are tested in the tox.ini file.
=> Clarify supported versions of Python 3

googleapiclient/http.py, tests/test_discovery.py
The client library depends on the range header being in the response when the HTTP response code is 308, but the range header is not present in the response when the server hasn't received any bytes previously. This PR defaults to 0 in that case.
=> Fix error in resumable upload handler

.travis.yml, googleapiclient/_auth.py, googleapiclient/discovery.py, setup.py, tests/test__auth.py, tests/test_discovery.py, tox.ini
This also obviates the need to pass credentials into `discovery.build` or `discovery.build_from_document` if you're using ADC. This library can now automatically acquire those.
=> Add support for google-auth

describe.py, googleapiclient/_auth.py, googleapiclient/discovery.py, googleapiclient/http.py, googleapiclient/sample_tools.py, tests/test__auth.py, tests/test_discovery.py, tests/test_http.py
This will avoid having hanging connections when using Google API calls.
In case the user have set default socket timeout, that value is used instead of default.
=> Set default timeout for all the HTTP requests

googleapiclient/discovery.py, tests/test_discovery.py
=> Don't invoke application default credentials logic when developerKey is provided

googleapiclient/discovery.py, googleapiclient/http.py, googleapiclient/model.py, googleapiclient/schema.py, tests/data/bigquery.json, tests/data/drive.json, tests/data/logging.json, tests/test_discovery.py
Addresses https://github.com/googleapis/toolkit/issues/692.
=> Fix generation for methods with abnormal page token conventions

googleapiclient/discovery.py, tests/test_discovery.py
=> Raise ValueError if credentials and developerKey are both specified

googleapiclient/http.py, tests/test_discovery.py, tests/test_http.py
Applies also for `MediaUploadProgress`.
Resolves: #369
=> ZeroDivisionError when calling 'MediaDownloadProgress.progress'

samples/django_sample/Makefile, samples/django_sample/manage.py, samples/django_sample/plus/models.py, samples/django_sample/plus/views.py, samples/django_sample/requirements.txt, samples/django_sample/settings.py
Issues: #285 #314 
Adding requirements.txt
Creating Makefile
Fixing problems with newer versions of oauth2
Fixing bugs in django files
=> Fixing django-sample

googleapiclient/errors.py, tests/test_errors.py
For instance, the **googleapiclient.errors.HttpError** returns only the message and the status code. Adding the _error details_ on that would be useful and the error becomes slightly more verbose. In the response returned from the server, if the error body contains the **details** field, just show it together with the error message for more details. For example:
`<HttpError 400 when requesting http://example.org returned "country is required". Details: "error details">`
Resolves: #382
=> Fix details missing in googleapiclient.errors.HttpError

googleapiclient/_auth.py, tests/test_http.py
Closes #350, Supersedes #434
Note: This change reveals surprising behavior between default credentials and batches. If you allow `googleapiclient.discovery.build` to use default credentials *and* specify different credentials by providing `batch.execute()` with an explicit `http` argument, your individual requests will use the default credentials and *not* the credentials specified to the batch http. To avoid this, tell `build` explicitly not to use default credentials by specifying `build(..., http=httplib2.Http()`.
For context, see:
https://github.com/google/google-api-python-client/pull/434#issuecomment-358439456
=> Proactively refresh credentials when applying and treat a missing access_token as invalid.

googleapiclient/http.py
The current `DEFAULT_CHUNK_SIZE` of 512kb leads to unnecessarily slow
transfers, as in googlecolab/backend-container#1. Increasing this simply
lowers the overhead for large transfers.
Fixes #481.
PTAL @jonparrott -- I couldn't think of a meaningful test that didn't involve basically repeating the constant in another file, which feels silly. :grinning:
=> Increase the default media chunksize to 100MB.

googleapiclient/http.py
=> Warn when constructing BatchHttpRequest using the legacy batch URI

README.md
=> Promote GCP APIs

googleapiclient/_helpers.py, googleapiclient/channel.py, googleapiclient/discovery.py, googleapiclient/errors.py, googleapiclient/http.py, googleapiclient/sample_tools.py, googleapiclient/schema.py, tests/test__helpers.py, tests/test_discovery.py
oauth2client is deprecated
Migrate required helper's code from oauth2client to googleapiclient to
decrease our dependency on oauth2client
_helpers.py copied from oauth2client code
https://github.com/google/oauth2client/blob/master/oauth2client/_helpers.py
=> Remove oauth2client._helpers dependency

googleapiclient/http.py, tests/test_http.py
resolves https://github.com/google/google-api-python-client/issues/494
=> fix socket.timeout retry

googleapiclient/discovery.py, tests/test_discovery.py
Fixes #416.
I made body optional instead of not adding it at all for backward compatibility.
=> Make body optional for requests with no parameters

.travis.yml, googleapiclient/discovery_cache/file_cache.py, setup.py, tests/__init__.py
oauth2client is deprecated, use google-auth instead
Closes #437
=> Drop oauth2client dependency 

apiclient/__init__.py
oauth2client is not even a required dependency now, so this check throws a confusing error message
This sort of fixes #521, but I still can't import `apiclient.discovery` without having `oauth2client` installed:
```
>>> from apiclient import discovery
Traceback (most recent call last):
File "/Users/epall/projects/google-api-python-client/googleapiclient/sample_tools.py", line 32, in <module>
from oauth2client import client
ModuleNotFoundError: No module named 'oauth2client'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/epall/projects/google-api-python-client/apiclient/__init__.py", line 13, in <module>
from googleapiclient import sample_tools
File …
```
=> Remove check for a failed googleapiclient upgrade

apiclient/__init__.py
It depends heavily on oauth2client, which has been dropped as a required dependency
This seems to me like the quickest way to tackle #524, but it feels ugly. Maybe `sample_tools` needs to get re-written to use `google-auth`?
=> Make apiclient.sample_tools optional

googleapiclient/sample_tools.py, samples/maps_engine/maps_engine.py, samples/prediction/prediction.py
Prevent stray imports of older 'apiclient' alias from raising an ImportError if oauth2client is not installed, unless sample_tools.init is actually called.
Closes #524
=> Make oauth2client even more optional.

googleapiclient/http.py, tests/test_http.py
Closes #164 
Closes #536
Also ensures that things don't break if a user supplies a request_id with a "+" in it.
=> Fix #164 under Python 3; prevent line-folding at beginning of content-id header

tests/test_http.py
`xrange` does not exist in Python 3 and this is causing Python 3 tests to fail.
=> Change xrange to range

googleapiclient/http.py
This should allows for `set_user_agent` and `tunnel_patch` to be used with an instance of google-auth-library-python-httplib's [AuthorizedHttp](https://github.com/GoogleCloudPlatform/google-auth-library-python-httplib2/blob/e7cd722281d1d897fa9ae6e3b6b78ae142778e6e/google_auth_httplib2.py#L178).
Closes #656.
=> Call original request method with kwargs.

README.md, docs/README.md, docs/api-keys.md, docs/auth.md, docs/client-secrets.md, docs/django.md, docs/google_app_engine.md, docs/logging.md, docs/media.md, docs/mocks.md, docs/oauth-installed.md, docs/oauth-server.md, docs/oauth-web.md, docs/oauth.md, docs/pagination.md, docs/performance.md, docs/start.md, docs/thread_safety.md
This PR adds all guides that used to live on https://developers.google.com/api-client-library/python/ to this repo. The content is not changed besides change the HTML into md. Note: Some of content may be out of date since most of it was authored in 2015.
- Moves the API guides from the [old site](https://developers.google.com/api-client-library/python/) to this repo.
- Formats all docs in markdown (instead of HTML) for easy manipulation
- All docs are now open source, meaning anybody can comment and fix them!
- Adds a link to the homepage to the `docs` folder.
- Adds a `docs/README.md` navigation homepage.
---
B: #669 #670 #671 #672 #673 #674 #675 #676 #677 #678 #679 #680 #681 #682 #683 #684 #685 #686 #687 #688 #689 #690 #693.
R: @busunkim96
=> docs: Adds docs folder

googleapiclient/discovery.py, tests/test_discovery.py
Fixes #713. 
Never require that a `body` be passed in a request. Validation of `body` will be left to the server.
=> Never require 'body' for requests.

googleapiclient/http.py, tests/test_http.py
=> Make http.MediaFileUpload close its file descriptor.

googleapiclient/http.py, samples/coordinate/coordinate.py, tests/test_http.py
=> Fix http.py: Exception -> exception.

docs/oauth.md
While working through the docs I noticed the link to `client_secrets.json` documentation was giving a 404. The issue was the filename in git is `client-secrets.md` not `client_secrets.md`.
Thanks for these docs, I'm finding them really helpful!
=> Fixing typo in filename

googleapiclient/model.py, tests/test_http.py, tests/test_json_model.py
=> Pass library and Python version in x-goog-api-client

googleapiclient/errors.py
Some APIs return 'detail' instead of 'details'. This leads to unhelpful messages like `Request contains an invalid argument.`.
=> Look for field 'detail' in error response.

docs/start.md
On the getting started page, change link to API explorer to
https://developers.google.com/apis-explorer/.
=> docs: fix link to API explorer

docs/oauth-installed.md
I noticed a small typo in a code snippet from the OAuth docs. 
The the class method [`google_auth_oauthlib.flow.InstalledAppFlow.from_client_secrets_file `](https://github.com/googleapis/google-auth-library-python-oauthlib/blob/master/google_auth_oauthlib/flow.py#L182) has two args `client_secrets_file` and `scopes`.
Hope this helps 👋
=> docs: fix argument typo in code example

README.md
Copied from google-cloud-python install docs: https://github.com/googleapis/google-cloud-python/blob/master/storage/README.rst
=> docs: recommend install with virtualenv

docs/README.md
Library was spelt `LIbrary` with both L and I capitalized
=> chore(docs): fix capitalization in docs/README.md

README.md
Hello,
We have a dedicated library for the Googlle Ads service. I think it is worth adding it to README.md.
Best regards,
Kamil
CC: @BenRKarl, @wihl
=> Add note about Google Ads llibrary

googleapiclient/http.py, setup.py
This allows folks who can't upgrade their httplib2 version to use the latest version of the library. Note that it is still strongly recommended that you upgrade (see [install_requires](https://github.com/googleapis/google-api-python-client/blob/master/setup.py#L36)). 
@aaltay is there an issue tracking the httplib2 upgrade I can link to? I'd like this to be removed eventually.
=> fix: don't set http.redirect_codes if the attr doesn't exist

googleapiclient/http.py, googleapiclient/model.py
This change fixes a few error prone interactions with `str` and `bytes` type objects which surface as exceptions when the `googleapiclient` library tests are run with the `-bb` command line flag
See https://docs.python.org/3/using/cmdline.html#cmdoption-b
=> Fix "byteswarning" errors in http and model modules

googleapiclient/discovery.py
The Healthcare API has a resource named 'Patient-everything' which is unaccessible because the hyphen makes it an invalid name.
https://healthcare.googleapis.com/$discovery/rest?version=v1
```
"Patient-everything": {
"response": {
"$ref": "HttpBody"
},
```
This change replaces the '-' with a '_'.
```py
from googleapiclient import discovery
service = discovery.build("healthcare", "v1")
service.projects().locations().datasets().fhirStores().fhir().Patient_everything(name='...')
```
CC @noerog
=> fix: replace '-' in method names with '_'

apiclient/__init__.py
Hello,
We have removed __version__ var from googleapiclient/__init__.py
https://github.com/googleapis/google-api-python-client/commit/f706cfd821ab7457e5db37abfc3619772657dd0e#diff-b926d296d4c856bcbf877809e4523562L15
so it won't work anymore.
https://github.com/googleapis/google-api-python-client/issues/870
CC: @busunkim96
Fixes #870 🐈
=> Remove apiclient.__version__

README.md
3.4 is no longer being tested and has been removed from the setup.py
=> docs: drop 3.4 from README

CHANGELOG.md, setup.py
Manually constructed as I couldn't get release-please to appear. 
I kept the release-please format. See https://github.com/googleapis/google-api-python-client/pull/868/files
=> chore: release 1.8.2

googleapiclient/discovery.py
Reopens #782 from @bsolomon1124 as that branch is now gone.
The current INFO calls, which are highly repetitive, don't meet
the typical 'severity level' of an INFO message, and are more suited
for DEBUG.
Refs Issue #781
=> fix: downgrade repetitive logging calls to debug

tests/test_discovery.py
Our tests were passing because `GOOGLE_APPLICATION_CREDENTIALS` are in the environment, but this should technically use mock credentials.
=> test: use self.MOCK_CREDENTIALS in tests

googleapiclient/discovery_cache/__init__.py, tests/test_discovery.py
The GAE memcache API isn't supported in python3. This change gives
callers a new way to ensure that googleapiclient doesn't even try
to import and use this legacy API.
Fixes #902 🦕
=> fix: don't try to import GAE API in other environments

googleapiclient/http.py
Fixes the date of when the global batch endpoint will be turned down, per the extension outlined in https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html.
=> fix: the turn down date for global batch uri

googleapiclient/discovery.py, setup.py
`ClientOptions` doesn't have `client_encryted_cert_source` property yet. Check the existence of the property before accessing it.
=> fix: fix python-api-core dependency issue

noxfile.py, setup.py
bump api-core version to take `client_encrypted_cert_source` from `ClientOptions`.
=> fix: bump api-core version

googleapiclient/discovery.py, tests/test_discovery.py
Go client used lower case, so change the values to lower case in python apiary client.
=> fix: update GOOGLE_API_USE_MTLS values

googleapiclient/discovery.py, tests/test_discovery.py
For googleapis/python-api-core#14
=> feat: allow to use 'six.moves.collections_abc.Mapping' in 'client_options.from_dict()'

setup.cfg
See https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels
Fixes #<issue_number_goes_here> 🦕
=> feat: Build universal wheels

.gitignore, googleapiclient/discovery.py, googleapiclient/http.py, tests/data/500.json, tests/data/503.json, tests/test_discovery.py, tests/test_http.py
Adding ability for discovery to retry on eligible http errors
and connection problems with randomized exponential backoff.
Also:
* DRYing discovery tests to avoid warnings when reading test data.
* Updating .gitignore
Fixes: #848
=> feat: discovery supports retries

googleapiclient/discovery.py, tests/test_discovery.py
Passing version=None to discovery.build(), with intent to always
get the latest version of the discovery document,
no longer attempts to use Discovery V1, which fails with
Bad Request errors.
Instead, it uses Discovery V2, which supports null version use case.
Fixes: #971
=> fix: discovery uses V2 when version is None

describe.py
=> docs: fix deprecation warnings due to invalid escape sequences.

docs/oauth-server.md
fixed link based on https://developers.google.com/identity/protocols/oauth2/service-account
=> docs: fix link to service accounts documentation

docs/batch.md
`http=http` is optional
Fixes #1002  🦕
=> docs: remove http from batch execute docs

googleapiclient/_auth.py, googleapiclient/discovery.py, noxfile.py, setup.py, tests/test__auth.py, tests/test_discovery.py, tests/test_http.py
Add support for client options:
* quota_project_id
* credentials_file
* scopes
These are only available when default credentials are used.
=> feat: add quota_project, credentials_file, and scopes support

googleapiclient/http.py, tests/test_http.py
Fixes #638 🦕
Setting the `content-range` header on an empty resumable upload results in 400 Invalid Argument. Only set the `content-range` if there is content. This is what the Java discovery client does ([code](https://github.com/googleapis/google-api-java-client/blob/326370e0ec4351aaea21da271692b2fb9585a28c/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpDownloader.java#L242-L255)).
TODO:
=> fix: don't set content-range on empty uploads

googleapiclient/http.py, tests/test_http.py
Don't raise on 416 Range Not Satisfied if there is no content to download. This is similar to fix in resumable media https://github.com/googleapis/google-resumable-media-python/pull/86/.
Fixes #638
=> fix: don't raise when downloading zero byte files

docs/start.md, googleapiclient/errors.py, tests/test_errors.py, tests/test_http.py
=> docs: Change error parsing to check for 'message'

googleapiclient/http.py
Fixes #1116 🦕
Don't throw invalid JSON messages for valid JSON.
=> fix: handle error on service not enabled

docs/oauth-server.md
Link out to cloud.google.com docs on service accounts since it is less likely to go stale.
Fixes #946
=> docs: update guidance on service accounts

googleapiclient/discovery_cache/__init__.py
=> fix: Use logging level info when file_cache is not available

describe.py, googleapiclient/discovery.py, googleapiclient/schema.py, tests/test_schema.py
=> docs: Reduce noisy changes in docs regen

describe.py
=> docs: fix regression with incorrect args order in docs

googleapiclient/http.py, tests/test_http.py
=> fix: Catch ECONNRESET and other errors more reliably

googleapiclient/http.py, tests/test_http.py
=> fix: replace deprecated socket.error with OSError

setup.py
For consistency with google-api-core, which specifies
`google-auth >= 1.21.1, < 2.0dev` as a dependency.
Fixes #1179 🦕
=> fix(deps): add upper-bound google-auth dependency

setup.py, tests/test__auth.py
As python 2.7 is no longer supported in master, this fix is only intended for the [v1](https://github.com/googleapis/google-api-python-client/tree/v1) branch where we still have support for python 2.7.
Fixes #1204 🦕
=> chore(v1): Pin rsa to 4.5 for Python 2.7 compatibility

MANIFEST.in
Fixes #1214 
The [MANIFEST.in](https://packaging.python.org/guides/using-manifest-in/) controls which files are included in the published package.
You can verify that this fixes the problem (missing discovery docs leading to failing `discovery.build()` calls) by building the package and installing the library from the tarfile.
- `python3 -m venv env`
- `source env/bin/activate`
- `python3 -m setup.py sdist`
- `python3 -m pip install dist/google-api-python-client-2.0.0.tar.gz`
```
(env) busunkim@busunkim:~/github/google-api-python-client$ python3
Python 3.6.9 (default, Feb 24 2020, 21:10:07) 
[GCC 9.2.1 20190909] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import googleapiclient
>>> from googleapiclient import discovery
>>> client = …
```
=> fix: add static discovery docs 

setup.py
Fixes #1214  🦕
I was able to re-create the issue by using the following steps.
1) Create a clean `pyenv` environment
2) Download google-api-python-client-2.0.1 from PyPi [here](https://files.pythonhosted.org/packages/dc/67/a228c05a28288fdfde6e8c1a27a62e10ee265664c0f1d59070e6e0dc6242/google-api-python-client-2.0.1.tar.gz) and unzip it
3) Install it using `pip install <Unzipped Directory>`
4) Confirm `discovery.build()` fails on any call
To Verify the fix, repeat the steps above, but apply the update in this PR prior to installing the library.
=> fix: Include discovery artifacts in published package

README.md, UPGRADING.md
Update README to promote [cloud client libraries](https://github.com/googleapis/google-cloud-python) for new code development for the following reasons:
- There is a separate client library for each API, so you can choose
which client libraries to download. Whereas, `google-api-python-client` is a
single client library for all APIs. As a result, the total package size for
`google-api-python-client` exceeds 50MB.
- There are stricter controls for breaking changes to the underlying APIs
as each client library is focused on a specific API.
- There are more features in these Cloud Client Libraries as each library is
focused on a specific API, and in some cases, the libraries are owned by team
who specialized in that API.
- Developers will benefit from intellisense.
Fixes #1239 🦕
=> docs: Update README to promote cloud client libraries

UPGRADING.md, googleapiclient/discovery.py, tests/test_discovery.py
=> fix: Change default of `static_discovery` when `discoveryServiceUrl` set

googleapiclient/errors.py, tests/test_errors.py, tests/test_http.py
=> feat: Adds support for errors.py to also use 'errors' for error_details 

noxfile.py, setup.py
Fixes #1235 🦕
In an attempt to verify that this is a fix for #1235  I'm going push a commit that removes the fix from #1221 in this PR and confirm that the checks fail.
=> test: update nox file to build and test wheels

tests/test_discovery.py
We don't actually want to exercise ADC in this unit tests, so pass a mock credential object instead.
=> test: always use MOCK_CREDENTIALS in tests

.github/workflows/main.yml
=> chore: Prevent Github action from running on forks

.github/workflows/main.yml
PR #1343 was supposed to fix #1342 but the issue still persists. See [this](https://github.com/parthea/google-api-python-client/actions/runs/824759723) github action from my fork.
The root cause turned out to be the multiline format of the `if` statement of `main.yml`. I expected the pipe `|` character to allow `if` statements to be used in a multiline format however the actual behaviour is different than I expected. This PR converts the check to a single line `if` statement.
Using the fix in this PR the workflow was correctly skipped in parthea/google-api-python-client/pull/1.
=> chore: fix if statement in github workflow

.github/CODEOWNERS
Adds @yoshi-approver to CODEOWNERS so PRs like [this](https://github.com/googleapis/google-api-python-client/pull/1359) can be auto-approved.
=> chore: Add @yoshi-approver to CODEOWNERS

.github/CODEOWNERS
PR https://github.com/googleapis/google-api-python-client/pull/1372 for updating static discovery artifacts wasn't approved automatically. The issue is that `/docs/dyn/index.md` was not in the `CODEOWNERS` file due to a copy paste error in https://github.com/googleapis/google-api-python-client/pull/1360.
=> chore: fix CODEOWNERS typo for /docs/dyn/index.md

describe.py
Fixes #1384
This PR is also a partial fix for #1330 where there are duplicate discovery artifacts for the same API and version. The issue is that in `describe.py` there is a call to `safe_version()` which is changing the version to remove decimal places.
For example, the following artifacts exist
https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/adexchangebuyer.v1.2.json
https://github.com/googleapis/google-api-python-client/blob/master/googleapiclient/discovery_cache/documents/adexchangebuyer.v12.json
For `adexchangebuyer` version `v.1.2`, instead of  this
```
from googleapiclient.discovery import build
build('adexchangebuyer', 'v1.2')
```
we would have this.
```
from googleapiclient.discovery import build …
```
=> fix: resolve issue where certain artifacts would not be updated

googleapiclient/discovery.py, tests/test_discovery.py
The content-length header only gets updated at request object initialization, so make sure we update it here after we modified the body.
Fixes #1403
=> fix: update content-length header for next page requests

.github/workflows/main.yml
Right now the Github Action that updates discovery artifacts runs every day at 7 am UTC. Since we typically only release `google-api-python-client` once per week, I'd like to modify the action to only update discovery artifacts once per week.
=> chore: Limit Github Action to run once per week

.github/CODEOWNERS, .github/auto-approve.yml, .github/workflows/main.yml, .kokoro/build.sh, .kokoro/test-samples-impl.sh, .repo-metadata.json, CONTRIBUTING.rst, README.md, docs/mocks.md, owlbot.py, scripts/updatediscoveryartifacts.py
Towards https://github.com/googleapis/google-cloud-python/issues/10579
=> chore: migrate default branch from master to main

googleapiclient/errors.py
self._get_reason is being called in \_\_init\_\_ (https://github.com/googleapis/google-api-python-client/pull/1185)  , so why not save it then?
also in the \_\_repr\_\_ function we got the reason by calling the _get_reason function right in the beginning, but was then called again.
=> fix: remove repeated calls to self._get_reason

.repo-metadata.json
Both `default_version` and `codeowner_team` have empty strings for this repo. By default the code owner will be googleapis/yoshi-python. This change is needed for the following synthtool PRs. 
https://github.com/googleapis/synthtool/pull/1201
https://github.com/googleapis/synthtool/pull/1114
=> chore: add default_version and codeowner_team to .repo-metadata.json

googleapiclient/discovery.py, tests/data/service_account.json, tests/test_discovery.py
Enable self signed jwt if google-auth service account credentials are used.
Tested with Storage, Compute and PubSub APIs:
```
import googleapiclient.discovery
project = "<project>"
zone = "us-west1-a"
compute = googleapiclient.discovery.build('compute', 'v1')
result = compute.instances().list(project=project, zone=zone).execute()
print(result)
storage = googleapiclient.discovery.build('storage', 'v1')
result = storage.buckets().list(project=project).execute()
print(result)
topic = "<topic>"
pubsub = googleapiclient.discovery.build('pubsub', 'v1')
result = pubsub.projects().topics().get(topic=f"projects/{project}/topics/{topic}").execute()
print(result)
```
=> feat: enable self signed jwt for service account credentials

googleapiclient/http.py, tests/test_http.py
Issue: It looks like Range header end value was constructed by adding chunk size to
current position. This leads into the request being one byte longer, and also
the received response body is one byte longer than anticipated.
Fix: adjust the end to be one byte earlier.
For example with `chunksize=1024` and current position being 0, the range header
should be set to `bytes=0-1023`.
See: https://httpwg.org/specs/rfc7233.html#rule.ranges-specifier
Fixes #1593
----
Fixes #1593 🦕
=> fix: MediaIoBaseDownload range header off-by-one

describe.py, setup.py
Fixes #1611
This is being merged to the **v1** branch and will be released manually to PyPI.
=> fix(deps): allow google-api-core 2.x for python 3 users

CHANGELOG.md, setup.py
* allow google-api-core 2.x for python 3 users ([#1649](https://www.github.com/googleapis/google-api-python-client/issues/1649))
=> chore: release 1.12.9

CHANGELOG.md, setup.py
1.12.9 was not released due to a bug in the release script which was fixed in #1657
=> chore: release 1.12.10

.github/workflows/main.yml
Reverts googleapis/google-api-python-client#1676 as the github workflow is failing.
=> chore(revert): revert update actions/github-script action to v5

googleapiclient/_helpers.py, googleapiclient/discovery.py
=> docs: fix typo and unnecessary word in docstring

CHANGELOG.md, googleapiclient/version.py
* use version.py instead of pkg_resources ([#1677](https://www.github.com/googleapis/google-api-python-client/issues/1677))
Also fixes version typo in https://github.com/googleapis/google-api-python-client/pull/1677
=> chore: release 1.12.11

apiclient/__init__.py, describe.py, googleapiclient/discovery_cache/__init__.py, googleapiclient/discovery_cache/file_cache.py, samples/adexchangeseller/get_all_alerts.py, samples/adexchangeseller/get_all_dimensions.py, samples/adexchangeseller/get_all_metrics.py, samples/adexchangeseller/get_all_preferred_deals.py, samples/analytics/hello_analytics_api_v3.py, samples/analytics/management_v3_reference.py, samples/appengine/main.py, samples/storage_serviceaccount_appengine/main.py, scripts/buildprbody.py, scripts/buildprbody_test.py, tests/test_discovery.py, tests/test_discovery_cache.py
Fixes warnings from `flake8 . --select F401`
```
(py39) partheniou@partheniou-vm-2:~/git/google-api-python-client$ flake8 . --select F401
./describe.py:37:1: F401 'googleapiclient.discovery.build' imported but unused
./googleapiclient/discovery_cache/file_cache.py:30:1: F401 'threading' imported but unused
./googleapiclient/discovery_cache/__init__.py:19:1: F401 'datetime' imported but unused
./googleapiclient/discovery_cache/__init__.py:40:13: F401 'google.appengine.api.memcache' imported but unused
./scripts/buildprbody.py:15:1: F401 'enum.IntEnum' imported but unused
./scripts/buildprbody_test.py:20:1: F401 'shutil' imported but unused
./scripts/buildprbody_test.py:24:1: F401 'changesummary.ChangeType' imported but unused
./samples/adexchangeseller/get_all_preferred_deals.py:25:1: F401 …
```
=> chore: remove unused imports

testing/constraints-3.7.txt
Test the minimum supported dependencies in python 3.7 unit tests to prepare for dropping python 3.6
=> chore: test minimum dependencies in python 3.7

noxfile.py, tests/test__auth.py, tests/test__helpers.py, tests/test_discovery.py, tests/test_discovery_cache.py, tests/test_http.py
As of Python 3.4, the unittest module in the standard library has
included mock, which means we can remove one external dependency.
Fixes #1863
=> test: Switch to unittest.mock

googleapiclient/discovery_cache/file_cache.py, samples/analytics/management_v3_reference.py
There are small typos in:
- googleapiclient/discovery_cache/file_cache.py
- samples/analytics/management_v3_reference.py
Fixes:
- Should read `hierarchy` rather than `hiearchy`.
- Should read `accessing` rather than `accesing`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

UPGRADING.md
See the code below 
https://github.com/googleapis/google-api-python-client/blob/cb89554f28463ce707081aee95244127e963cfdf/googleapiclient/discovery.py#L270-L274
This PR proposes that we change the wording in `UPGRADING.md` from
```
if `static_discovery` is not
specified, the default value for `static_discovery` will be `True` when
the `discoveryServiceUrl` argument of `discovery.build()` is provided.
```
to
```
if `static_discovery` is not
specified, the default value for `static_discovery` will be `False` when
the `discoveryServiceUrl` argument of `discovery.build()` is provided.
```
=> docs: fix a typo in UPGRADING.md related to static_discovery

noxfile.py, tests/test__auth.py, tests/test_discovery.py, tests/test_http.py
Make it possible to run the test suite without oauth2client, by skipping the few tests that specifically require it.  Given that oauth2client is deprecated, we are aiming towards removing it entirely from Gentoo and the unconditional imports in the test suite are a blocker for that.
I've also added running without oauth2client as an additional nox scenarios but I can remove that if you prefer.
=> test: Support running the test suite without oauth2client

README.md
A link for WebTest in [README.md](https://github.com/googleapis/google-api-python-client/blob/main/README.md?plain=1#L113) is broken. According to [InternetArchive](http://web.archive.org/web/20160801000000*/http://webtest.pythonpaste.org/en/latest/index.html).
Can we use to [pypi.org](https://pypi.org/project/WebTest/) ?
=> docs: dead link to WebTest fixed in README.

setup.py
`httplib2<1dev` is ~not~ a valid version matcher (edit: it is valid, just doesn't parse with distlib) in the sense of [PEP 440](https://peps.python.org/pep-0440/).
> The canonical public version identifiers MUST comply with the following scheme:
> `[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`
It is also considered bad practice to have an upper bound on package versions and installers like pip do not consider development versions in any case (unless explicitly told to).
Fixes #2151
=> fix: remove faulty version matcher in setup.py

googleapiclient/discovery.py, tests/test_discovery.py
Fixes #2365 🦕
Towards b/324211188 🦕
=> feat: Allow users to configure client option `universe_domain`

describe.py, noxfile.py, scripts/updatediscoveryartifacts.py
=> build: fetch discovery artifacts from discovery-artifact-manager

setup.cfg
`setup.cfg` contains a setting to create a `Universal Wheel` which is only needed if libraries support both Python 2 and Python 3. This library only supports Python 3 so this setting is no longer needed. See https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#wheels.
See similar PR https://github.com/googleapis/google-cloud-python/pull/13659 which includes this stack trace
```
running bdist_wheel
/tmp/pip-build-env-9o_3w17v/overlay/lib/python3.13/site-packages/setuptools/_distutils/cmd.py:135: SetuptoolsDeprecationWarning: bdist_wheel.universal is deprecated
!!
********************************************************************************
With Python 2.7 end-of-life, support for building universal wheels
(i.e., wheels that support both Python 2 and …
```
=> fix: remove setup.cfg configuration for creating universal wheels
