googleapis/google-api-python-client

tests/test_channel.py
tests/test_discovery.py
tests/test_errors.py
tests/test_http.py
tests/test_json_model.py
tests/test_mocks.py
tests/test_model.py
tests/test_protobuf_model.py
tests/test_schema.py
tox.ini

Used for Python 2.6 compatibility in testing.

Using unittest2 in place of unittest

---

.travis.yml

Ref http://docs.travis-ci.com/user/caching/#pip-cache

Enable travis caching for pip cache

---

README.md

PTAL @wescpy or @nathanielmanistaatgoogle ?

Update README.md to mention python3 support.

---

samples/blogger/blogger.py

Now the blogger API sample is actually working.

Fix blogger API sample.

---

samples/README.md
samples/adsense/README
samples/adsense/README.md
samples/adsensehost/README
samples/adsensehost/README.md
samples/storage/README
samples/storage/README.md
samples/youtube/README
samples/youtube/README.md

Also updates stale documentation with informative links.

Add informative samples README.md

---

samples/README.md
samples/searchconsole/README
samples/searchconsole/client_secrets.json
samples/searchconsole/search_analytics_api_sample.py

1. Create directory Search Console API samples.
2. Add sample for Search Analytics API method (part of Search Console API).

Add Search Console (f.k.a Webmaster Tools) command line samples.

---

setup.py

I added a sub package in #127 but didn't add it to setup.py.
Fixes #128

Added 'googleapiclient/discovery_cache' to setup.py.

---

googleapiclient/discovery.py
tests/test_discovery.py

Fixed a NameError on exception, added a unit test.

---

contributing.html

Removing redundant name in GH paths

---

googleapiclient/discovery_cache/file_cache.py
samples/appengine/main.py
samples/django_sample/plus/models.py
samples/django_sample/plus/views.py
samples/service_account/tasks.py
samples/storage_serviceaccount_appengine/main.py
samples/tasks_appengine/main.py

A few modules moved to a contrib subpackage of oauth2client and sample code needed updating

Fix incompatibility with oauth2client v2.0.0

---

googleapiclient/http.py
tests/test_http.py

catch more socket error conditions leading to a retry

Retry requests on broken pipe and aborted connection (#218)

---

README.md

just a small update as they moved the httplib2 project to it's own github user.

Updates httplib2 link

---

googleapiclient/channel.py

Fix bad oauth2client util import

---

googleapiclient/errors.py

Handle error when it's list instead of dict https://github.com/google/google-api-python-client/issues/225

handle errors when received an array from api

---

googleapiclient/errors.py
tests/test_http.py

BatchError is unprintable using default constructor (#165)

---

setup.py

Update minimum httplib2 dependency

---

googleapiclient/_auth.py

Fixes https://github.com/google/google-api-python-client/issues/327

Adding import of google.auth.credentials to googleapiclient._auth module

---

README.md

Dead link to WebTest fixed in README.

---

googleapiclient/_auth.py
googleapiclient/http.py
tests/test_http.py
tox.ini

Fix credentials usage in BatchHTTPRequest

---

googleapiclient/http.py

Solves #450 
Updated the Docstring and corrected it for next_chunk()

Update Docstring (#1)

---

googleapiclient/discovery.py
tests/test_discovery.py

Remove mutual exclusivity check for developerKey and credentials

---

googleapiclient/http.py
tests/test_http.py

HttpRequest.__init__ remove useless mimeparse

---

googleapiclient/discovery.py

Update comment, fixes #408

---

MANIFEST.in

Include tests in source distribution

---

README.md

take suggestion by @charlesreid1 about better places to point to docs
Closes #503

Better docs links in readme

---

googleapiclient/channel.py

add copyright header to channel.py, closes #216

---

googleapiclient/channel.py

Updates the `channel.py` documentation for executing a stop on a channel subscription.

Updates documentation for stopping channel subscriptions

---

googleapiclient/discovery.py

Convert '$' in method name to '_'

---

samples/README.md

Remove Django Samples.

---

docs/batch.md

It looks like this was missed in the initial lift and shift. See #690. @grant

Import batch.md

---

docs/api-keys.md

fix: Update api-keys.md

---

googleapiclient/discovery.py

Decode service to utf-8.

---

samples/searchconsole/search_analytics_api_sample.py

Fix TypeError: search_analytics_api_sample.py #732

---

README.md

Hello,
We have a dedicated library for the Googlle Firebase Admin API. I think it is worth adding it to README.md.
Best regards,
Kamil
CC: @hiranya911

docs: Add note about Google Firebase Admin API

---

contributing.html

Add reference to Conventional Commits which is a blocking presubmit check.
Fixes #<issue_number_goes_here> 🦕

fix: update GitHub org to googleapis from google

---

googleapiclient/_helpers.py

docs: fix typo in positional method docstring

---

googleapiclient/discovery.py
tests/test_discovery.py

support the environment variables described in https://google.aip.dev/auth/4114

feat: add support for mtls env variables

---

docs/start.md

docs: convert `print` statement to function

---

setup.py

This is needed for collections_abc
Fixes #1029  🦕

fix(deps): require six>=1.13.0

---

docs/thread_safety.md

docs: fix typo in thread safety example code

---

tests/test__auth.py

build: Fix unittest TestAuthWithGoogleAuth::test_with_scopes_scoped

---

docs/oauth-installed.md

fix: correct api version in oauth-installed.md

---

noxfile.py
synth.py

chore: Remove docs session

---

docs/README.md

chore: fix typo in README.md

---

setup.py

Reverts googleapis/google-api-python-client#1292

chore(revert): "chore: prevent normalization of semver versioning"

---

.github/.OwlBot.lock.yaml
owlbot.py

chore: removing owlbot directives for conversion to main

chore: removing owlbot directives for conversion to main

---

owlbot.py

This change is required for https://github.com/googleapis/synthtool/pull/1201

chore: exclude codeowners template

---

googleapiclient/model.py
googleapiclient/version.py
setup.py
tests/test_json_model.py

fix: Use version.py instead of pkg_resources

---

samples/compute/README.md
samples/compute/create_instance.py
samples/compute/noxfile.py

Fixes #<issue_number_goes_here> 🦕

style: update import in docs, improve python idiomaticity

---

googleapiclient/discovery.py
tests/test_discovery.py

Towards #2365 🦕
Towards b/324211188 🦕

feat: validate credentials for universe before request

---

googleapiclient/version.py
noxfile.py
setup.py
testing/constraints-3.10.txt
testing/constraints-3.7.txt
testing/constraints-3.8.txt
testing/constraints-3.9.txt

BEGIN_COMMIT_OVERRIDE
fix(deps): require httplib2>=0.19.0 
fix(deps): require google-auth>=1.32.0
fix(deps): require google-auth-httplib2>=0.2.0
END_COMMIT_OVERRIDE

fix(deps): require httplib2>=0.19.0

---

README.md

Thank you for considering my Pull Request. I have noticed that our README lacks syntax highlighting in code blocks, which can make it slightly harder to read. To address this issue, I have added appropriate syntax highlighting annotations to the code blocks in the README. This small change could improve the readability and overall look of the documentation.
Here’s what I’ve done in this PR:
- Added `bash` for shell scripts and `batch` for Batch file segments in the README to enable syntax highlighting.
- Checked all code blocks to ensure they are now properly highlighted according to their context.
Fixes #2364 🦕

docs: Added syntax highlighting to README
